print("Hello world")
print(5**2 )
print("\n")
print("My name is Dominik Aicken")
print("My teacher's name is Ms. White")
print("The name of my school is King's High")
print("My age is 15")
print("I have 800+ hours in my favourite video game") #I have been playing this game since 2019
print("In 25 years it will be 2047")
print("In 100 years I will be 115 years old")
print(658/7)
print("The moon landing was 53 years ago")
print("My favourite videogame is Dead By Daylight")
print("My favourite classes are 11JAP and 11DTE")
print("\n")
print(5+10.0)
print(10-5.0)
print(5/2)
print(5//2)
print(5%2)
print("Hello"*5)
print("\n")
print("Never gonna give you up, never gonna let you down, never gonna run around and desert you, never gonna make you cry, never gonna say goodbye, never gonna tell a lie and hurt you")
print("May the Force \nbe with you.")
print("A string is a printed word in python, a string can be a word, letter or sentence printed in a python statement.")
print("An integer is a number printed out as a whole number in python.")
print("A float is like an integer - but it shows you the decimal numbers as well as the whole number.")
print(543.0/3.0)
print(543/3)
